apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: microservice-fullstack-frankfurt-cluster
  region: eu-central-1

vpc:
  id: vpc-b0bb65da
  sharedNodeSecurityGroup: sg-01ef98326ad650361
  subnets:
    private:
      eu-central-1b:
        id: subnet-0861019dc0bd50408
      eu-central-1c:
        id: subnet-04e9d038693cd0673

managedNodeGroups:
  - name: microservice-fullstack-frankfurt-nodegroup
    instanceType: m5.xlarge
    desiredCapacity: 1
    labels: { labeltype: cpu }
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true